-- Improved Database Schema with Security and Relationships
-- Designed for SHM Portal (Scoutisme Hassania Marocain)

-- ============================================================================
-- 1. NICHES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.niches (
    id              text PRIMARY KEY,
    name            text NOT NULL UNIQUE,
    description     text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now()
);

CREATE INDEX idx_niches_name ON public.niches(name);

-- ============================================================================
-- 2. TUTORS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.tutors (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            text NOT NULL DEFAULT 'parent',
    prenom          text NOT NULL,
    nom             text NOT NULL,
    cin             text UNIQUE,
    phone           text,
    email           text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    CHECK (type IN ('parent', 'tuteur', 'gardien'))
);

CREATE INDEX idx_tutors_cin ON public.tutors(cin);
CREATE INDEX idx_tutors_phone ON public.tutors(phone);
CREATE INDEX idx_tutors_email ON public.tutors(email);

-- ============================================================================
-- 3. APP_USERS TABLE (Main Users Table)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.app_users (
    id              text PRIMARY KEY,
    prenom          text NOT NULL,
    nom             text NOT NULL,
    password_hash   text NOT NULL,
    dob             date,
    phone           text,
    address         text,
    email           text,
    role            text,
    niche_id        text REFERENCES public.niches(id) ON DELETE SET NULL,
    niche_superieur boolean DEFAULT false,
    tutor_id        bigint REFERENCES public.tutors(id) ON DELETE SET NULL,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    last_login      timestamptz,
    is_active       boolean DEFAULT true,
    CHECK (role IN ('membre', 'chef_niche', 'sous_chef', 'admin'))
);

CREATE INDEX idx_app_users_niche_id ON public.app_users(niche_id);
CREATE INDEX idx_app_users_tutor_id ON public.app_users(tutor_id);
CREATE INDEX idx_app_users_role ON public.app_users(role);
CREATE INDEX idx_app_users_is_active ON public.app_users(is_active);
CREATE INDEX idx_app_users_created_at ON public.app_users(created_at);

-- ============================================================================
-- 4. USERS TABLE (Fallback/Alternative)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id              text PRIMARY KEY,
    prenom          text NOT NULL,
    nom             text NOT NULL,
    password_hash   text NOT NULL,
    dob             date,
    phone           text,
    address         text,
    email           text,
    role            text,
    niche_id        text REFERENCES public.niches(id) ON DELETE SET NULL,
    niche_superieur boolean DEFAULT false,
    tutor_id        bigint REFERENCES public.tutors(id) ON DELETE SET NULL,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    last_login      timestamptz,
    is_active       boolean DEFAULT true,
    CHECK (role IN ('membre', 'chef_niche', 'sous_chef', 'admin'))
);

CREATE INDEX idx_users_niche_id ON public.users(niche_id);
CREATE INDEX idx_users_tutor_id ON public.users(tutor_id);
CREATE INDEX idx_users_role ON public.users(role);
CREATE INDEX idx_users_is_active ON public.users(is_active);
CREATE INDEX idx_users_created_at ON public.users(created_at);

-- ============================================================================
-- 5. USER_CATEGORIES TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.user_categories (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         text NOT NULL REFERENCES public.app_users(id) ON DELETE CASCADE,
    category_code   text NOT NULL,
    created_at      timestamptz DEFAULT now(),
    UNIQUE(user_id, category_code)
);

CREATE INDEX idx_user_categories_user_id ON public.user_categories(user_id);
CREATE INDEX idx_user_categories_code ON public.user_categories(category_code);

-- ============================================================================
-- 6. PROGRAMMES TABLE (Activity Programs)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.programmes (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           text NOT NULL,
    description     text,
    niche_id        text REFERENCES public.niches(id) ON DELETE SET NULL,
    created_by      text REFERENCES public.app_users(id) ON DELETE SET NULL,
    start_date      date,
    end_date        date,
    status          text DEFAULT 'planifie',
    content         text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    CHECK (status IN ('planifie', 'en_cours', 'termine', 'annule'))
);

CREATE INDEX idx_programmes_niche_id ON public.programmes(niche_id);
CREATE INDEX idx_programmes_created_by ON public.programmes(created_by);
CREATE INDEX idx_programmes_status ON public.programmes(status);
CREATE INDEX idx_programmes_dates ON public.programmes(start_date, end_date);

-- ============================================================================
-- 7. PROJECTS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.projects (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           text NOT NULL,
    description     text,
    niche_id        text REFERENCES public.niches(id) ON DELETE SET NULL,
    created_by      text REFERENCES public.app_users(id) ON DELETE SET NULL,
    start_date      date,
    end_date        date,
    budget          decimal(10, 2),
    status          text DEFAULT 'planifie',
    location        text,
    objectives      text,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    CHECK (status IN ('planifie', 'en_cours', 'termine', 'annule'))
);

CREATE INDEX idx_projects_niche_id ON public.projects(niche_id);
CREATE INDEX idx_projects_created_by ON public.projects(created_by);
CREATE INDEX idx_projects_status ON public.projects(status);
CREATE INDEX idx_projects_dates ON public.projects(start_date, end_date);

-- ============================================================================
-- 8. PROJECT_MEMBERS TABLE (Team Members for Projects)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.project_members (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    user_id         text NOT NULL REFERENCES public.app_users(id) ON DELETE CASCADE,
    role            text DEFAULT 'membre',
    joined_at       timestamptz DEFAULT now(),
    UNIQUE(project_id, user_id)
);

CREATE INDEX idx_project_members_project_id ON public.project_members(project_id);
CREATE INDEX idx_project_members_user_id ON public.project_members(user_id);

-- ============================================================================
-- 9. PROGRAMME_SESSIONS TABLE (Actual Sessions/Meetings)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.programme_sessions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_id    bigint REFERENCES public.programmes(id) ON DELETE CASCADE,
    session_number  integer,
    date            date NOT NULL,
    duration        integer, -- in minutes
    location        text,
    notes           text,
    attendance      integer,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now()
);

CREATE INDEX idx_programme_sessions_programme_id ON public.programme_sessions(programme_id);
CREATE INDEX idx_programme_sessions_date ON public.programme_sessions(date);

-- ============================================================================
-- 10. REPORTS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.reports (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           text NOT NULL,
    type            text NOT NULL,
    niche_id        text REFERENCES public.niches(id) ON DELETE SET NULL,
    created_by      text REFERENCES public.app_users(id) ON DELETE SET NULL,
    programme_id    bigint REFERENCES public.programmes(id) ON DELETE SET NULL,
    project_id      bigint REFERENCES public.projects(id) ON DELETE SET NULL,
    content         text,
    month           integer,
    year            integer,
    status          text DEFAULT 'brouillon',
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    CHECK (status IN ('brouillon', 'soumis', 'approuve', 'rejete'))
);

CREATE INDEX idx_reports_niche_id ON public.reports(niche_id);
CREATE INDEX idx_reports_created_by ON public.reports(created_by);
CREATE INDEX idx_reports_type ON public.reports(type);
CREATE INDEX idx_reports_month_year ON public.reports(month, year);

-- ============================================================================
-- 11. AUDIT_LOG TABLE (Security & Tracking)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.audit_log (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         text REFERENCES public.app_users(id) ON DELETE SET NULL,
    action          text NOT NULL,
    table_name      text,
    record_id       text,
    changes         jsonb,
    ip_address      text,
    created_at      timestamptz DEFAULT now()
);

CREATE INDEX idx_audit_log_user_id ON public.audit_log(user_id);
CREATE INDEX idx_audit_log_action ON public.audit_log(action);
CREATE INDEX idx_audit_log_created_at ON public.audit_log(created_at);

-- ============================================================================
-- SECURITY: ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.programmes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Users can view their own profile
CREATE POLICY "Users can view their own profile"
    ON public.app_users FOR SELECT
    USING (auth.uid()::text = id);

-- Users can view public programmes
CREATE POLICY "Users can view programmes in their niche"
    ON public.programmes FOR SELECT
    USING (niche_id IS NOT NULL);

-- Only authors can update their own programmes
CREATE POLICY "Only authors can update programmes"
    ON public.programmes FOR UPDATE
    USING (auth.uid()::text = created_by);

-- ============================================================================
-- INITIAL DATA
-- ============================================================================

-- Insert default niches
INSERT INTO public.niches (id, name, description) VALUES
  ('actualites', 'Actualités', 'Section des actualités et nouvelles'),
  ('organisation', 'Organisation', 'Organisation et administration'),
  ('projet', 'Projet', 'Gestion des projets'),
  ('rapports', 'Rapports', 'Rapports et documentations'),
  ('lois', 'Lois', 'Lois et régulations')
ON CONFLICT (id) DO NOTHING;
